import Fastify, { type FastifyReply, type FastifyRequest } from 'fastify'
import cors from '@fastify/cors'
import multipart from '@fastify/multipart'
import staticPlugin from '@fastify/static'
import { createReadStream } from 'node:fs'
import { mkdir, writeFile } from 'node:fs/promises'
import { join } from 'node:path'
import { PassThrough } from 'node:stream'
import { randomUUID } from 'node:crypto'
import type pg from 'pg'
import { z } from 'zod'
import { createCaptcha, verifyCaptcha } from './captcha.js'
import { config } from './config.js'
import { db, query, redis, transaction } from './db.js'
import { createApiKey, createSessionToken, decrypt, encrypt, hashPassword, sha256, verifyPassword } from './security.js'
import { registerPaymentRoutes } from './payment-routes.js'
import { inferModelCategory, modelCategories } from './model-category.js'

type Session={userId:string;tenantId:string;email:string;name:string;role:string;permissions:string[]}
const tenantStatus=z.enum(['active','suspended','archived'])
const tenantLifecycleStatus=z.enum(['active','suspended','archived','expired'])
const tenantDate=z.string().trim().refine(v=>!Number.isNaN(Date.parse(v)),{message:'日期时间格式不合法'})
const userPassword=z.string().min(8,'密码至少 8 位').max(128,'密码最多 128 位')
const generateInitialPassword=()=>`Mesh-${randomUUID().replace(/-/g,'').slice(0,12)}!`
const tenantOwnerPermissions=['models:read','models:write','apikeys:manage','members:manage','plans:manage','payments:manage','dictionaries:manage','settings:manage'] as const
const hasPermission=(session:Session,code:string)=>session.permissions.includes('*')||session.permissions.includes(code)
function assertPermission(session:Session,code:string){if(!hasPermission(session,code))throw Object.assign(new Error(`缺少权限 ${code}`),{statusCode:403})}
const toTenantDate=(value?:string|null)=>value?new Date(value):null
const slugifyTenant=(value:string)=>value.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,80)||`tenant-${Date.now().toString(36)}`
type TenantAccessRow={status:string;valid_from:Date|string;valid_until:Date|string|null}
type LoginRow=TenantAccessRow&{id:string;email:string;name:string;password_hash:string;tenant_id:string;role:string;permissions:string[]}
function tenantUnavailable(row:TenantAccessRow){const now=Date.now(),from=new Date(row.valid_from).getTime(),until=row.valid_until?new Date(row.valid_until).getTime():null;return row.status!=='active'||from>now||(until!==null&&until<=now)}
async function validateRolePermissions(session:Session,permissions:string[]){const unique=[...new Set(permissions)];if(unique.length!==permissions.length)throw Object.assign(new Error('权限列表包含重复项'),{statusCode:400});if(unique.length){const rows=(await query<{code:string}>(`SELECT code FROM app.permissions WHERE code=ANY($1::varchar[])`,[unique])).rows;if(rows.length!==unique.length)throw Object.assign(new Error('包含未登记的权限代码'),{statusCode:400});if(!session.permissions.includes('*')&&unique.some(code=>!session.permissions.includes(code)))throw Object.assign(new Error('不能授予当前账号不具备的权限'),{statusCode:403})}return unique}
async function bootstrapTenantDefaults(c:pg.PoolClient,tenantId:string){const owner=(await c.query(`INSERT INTO app.roles(tenant_id,name,description,is_system,permissions) VALUES($1,'所有者','租户工作空间全部权限',true,$2) ON CONFLICT(tenant_id,name) DO UPDATE SET permissions=EXCLUDED.permissions RETURNING id`,[tenantId,JSON.stringify(tenantOwnerPermissions)])).rows[0] as {id:string};await c.query(`INSERT INTO app.roles(tenant_id,name,description,is_system,permissions) VALUES($1,'成员','默认只读权限',true,$2) ON CONFLICT(tenant_id,name) DO UPDATE SET permissions=EXCLUDED.permissions`,[tenantId,JSON.stringify(['models:read'])]);const plan=(await c.query(`SELECT id FROM app.plans WHERE code='newer' AND active=true LIMIT 1`)).rows[0] as {id:string}|undefined;if(plan)await c.query(`INSERT INTO app.subscriptions(tenant_id,plan_id,provider,provider_ref,status,period_start,period_end) VALUES($1,$2,'manual','tenant-default','active',now(),now()+interval '1 month') ON CONFLICT DO NOTHING`,[tenantId,plan.id]);const dicts=[['order_status','订单状态',[['待支付','pending','#f59e0b'],['已支付','paid','#10b981'],['已取消','cancelled','#94a3b8'],['已退款','refunded','#ef4444']]],['member_status','成员状态',[['正常','active','#10b981'],['已邀请','invited','#f59e0b'],['已禁用','disabled','#94a3b8']]]] as const;for(const [code,name,items] of dicts){const d=(await c.query(`INSERT INTO app.dictionaries(tenant_id,code,name) VALUES($1,$2,$3) ON CONFLICT(tenant_id,code) DO UPDATE SET name=EXCLUDED.name RETURNING id`,[tenantId,code,name])).rows[0];let sort=0;for(const [label,value,color] of items)await c.query(`INSERT INTO app.dictionary_items(tenant_id,dictionary_id,label,value,color,sort_order) VALUES($1,$2,$3,$4,$5,$6) ON CONFLICT(dictionary_id,value) DO UPDATE SET label=EXCLUDED.label,color=EXCLUDED.color,sort_order=EXCLUDED.sort_order`,[tenantId,d.id,label,value,color,++sort])}return owner.id}
declare module 'fastify' { interface FastifyRequest { session?: Session; rawBody?: string } }
const app=Fastify({logger:true,bodyLimit:100*1024*1024})
await app.register(cors,{origin:config.appUrl,credentials:true}); await app.register(multipart,{limits:{fileSize:10*1024*1024,files:500,parts:1100}}); await mkdir(config.uploadDir,{recursive:true})
app.addHook('preParsing',async(request,_reply,payload)=>{if(!request.url.startsWith('/api/billing/webhooks/'))return payload;const chunks:Buffer[]=[];const stream=new PassThrough();payload.on('data',chunk=>chunks.push(Buffer.isBuffer(chunk)?chunk:Buffer.from(chunk)));payload.on('end',()=>{request.rawBody=Buffer.concat(chunks).toString('utf8')});payload.on('error',err=>stream.destroy(err));payload.pipe(stream);return stream})
const ok=(data:unknown)=>({data}); const tokenOf=(r:FastifyRequest)=>r.headers.authorization?.replace(/^Bearer\s+/,'')
type ProviderProtocol='openai'|'anthropic'|'ollama'|'custom'
type ProviderRecord={id:string;tenant_id:string;base_url:string;protocol:ProviderProtocol;auth_type:string;encrypted_api_key?:string|null}
function providerHeaders(protocol:ProviderProtocol,authType:string,key?:string){const headers:Record<string,string>={Accept:'application/json'};if(key&&authType==='bearer')headers.Authorization=`Bearer ${key}`;if(key&&(authType==='x-api-key'||protocol==='anthropic')){headers['x-api-key']=key;headers['anthropic-version']='2023-06-01'}return headers}
function providerErrorDetail(raw:string){if(!raw)return '';try{const json=JSON.parse(raw) as {message?:unknown;error?:unknown};if(typeof json.message==='string')return json.message;if(typeof json.error==='string')return json.error;if(json.error&&typeof json.error==='object'&&'message' in json.error&&typeof json.error.message==='string')return json.error.message}catch{}return raw.replace(/\s+/g,' ').trim().slice(0,300)}
async function throwProviderResponseError(response:Response,service:string):Promise<never>{const detail=providerErrorDetail(await response.text());throw new Error(`${service}服务返回 ${response.status}${detail?`：${detail}`:''}`)}
type DiscoveredModel={id:string;name?:string}
function parseDiscoveredModels(protocol:ProviderProtocol,json:unknown):DiscoveredModel[]{const value=json as {data?:unknown;models?:unknown};const list=Array.isArray(json)?json:protocol==='ollama'?value?.models:value?.data??value?.models;if(!Array.isArray(list))return [];return list.flatMap(item=>{if(typeof item==='string')return [{id:item,name:item}];if(!item||typeof item!=='object')return [];const model=item as {id?:unknown;name?:unknown;model?:unknown;display_name?:unknown};const id=typeof model.id==='string'?model.id:typeof model.model==='string'?model.model:typeof model.name==='string'?model.name:'';if(!id)return [];const name=typeof model.display_name==='string'?model.display_name:typeof model.name==='string'?model.name:id;return [{id,name}]})}
async function discoverProviderModels(provider:ProviderRecord,key?:string){const base=provider.base_url.replace(/\/+$/,'');const url=provider.protocol==='ollama'?`${base}/api/tags`:`${base}/models`;let response:Response;try{response=await fetch(url,{headers:providerHeaders(provider.protocol,provider.auth_type,key),signal:AbortSignal.timeout(12000)})}catch(e){throw Object.assign(new Error(`无法连接模型服务：${e instanceof Error?e.message:'网络错误'}；请确认服务地址可从当前服务端访问`),{statusCode:502})}if(!response.ok){const detail=providerErrorDetail(await response.text()),authFailed=response.status===401||response.status===403,statusCode=authFailed?400:response.status===429?429:502;const summary=authFailed?'API Key 无效或无权访问模型列表':response.status===429?'模型服务请求过于频繁或额度不足':`模型服务返回 ${response.status}`;throw Object.assign(new Error(`${summary}${detail?`：${detail}`:''}`),{statusCode})}let json:unknown;try{json=await response.json()}catch{throw Object.assign(new Error('模型服务返回了无法解析的响应，请确认 Base URL 指向兼容 API（通常以 /v1 结尾）'),{statusCode:502})}const models=parseDiscoveredModels(provider.protocol,json);if(!models.length)throw Object.assign(new Error('模型服务未返回可用模型；请确认 Base URL 包含正确的 API 版本路径，或手工填写模型 ID'),{statusCode:502});return models}
async function saveProviderModels(tenantId:string,providerId:string,models:DiscoveredModel[]){const unique=[...new Map(models.map(model=>[model.id.trim(),{id:model.id.trim(),name:(model.name??model.id).trim()}])).values()];const invalid=unique.find(model=>!model.id||model.id.length>150||!model.name||model.name.length>150);if(invalid)throw Object.assign(new Error(`模型列表包含不合法或过长的模型标识：${invalid.id.slice(0,80)}`),{statusCode:502});const existing=(await query<{external_id:string}>(`SELECT external_id FROM app.models WHERE tenant_id=$1 AND provider_id=$2`,[tenantId,providerId])).rows,existingIds=new Set(existing.map(model=>model.external_id)),additional=unique.filter(model=>!existingIds.has(model.id)).length;try{await enforceResourceQuota(tenantId,'models',additional)}catch(e){if((e as {statusCode?:number}).statusCode===429){const entitlements=await currentEntitlements(tenantId),limit=typeof entitlements.models==='number'?entitlements.models:null,used=(await query<{used:number}>(`SELECT count(*)::int used FROM app.models WHERE tenant_id=$1`,[tenantId])).rows[0].used;if(limit!==null)throw Object.assign(new Error(`中转站返回 ${unique.length} 个模型，需新增 ${additional} 个；当前套餐模型额度 ${used}/${limit}，剩余 ${Math.max(0,limit-used)} 个。请减少手工模型 ID 或升级套餐`),{statusCode:429})}throw e}await transaction(async c=>{for(const model of unique)await c.query(`INSERT INTO app.models(tenant_id,provider_id,external_id,name,model_category,context_window) VALUES($1,$2,$3,$4,$5,131072) ON CONFLICT(provider_id,external_id) DO UPDATE SET name=EXCLUDED.name,enabled=true`,[tenantId,providerId,model.id,model.name,inferModelCategory(model.id,model.name)])});return unique.length}
async function auth(r:FastifyRequest,reply:FastifyReply){const token=tokenOf(r);if(!token)return reply.code(401).send({error:'unauthorized',message:'请先登录'});const sessionKey=`session:${sha256(token)}`,raw=await redis.get(sessionKey);if(!raw)return reply.code(401).send({error:'session_expired',message:'登录已过期'});r.session=JSON.parse(raw);const tenant=(await query<TenantAccessRow>(`SELECT status,valid_from,valid_until FROM app.tenants WHERE id=$1`,[r.session!.tenantId])).rows[0];if(!tenant||tenantUnavailable(tenant)){await redis.del(sessionKey);return reply.code(403).send({error:'tenant_unavailable',message:'租户已停用或不在有效期内'})}await redis.expire(sessionKey,86400)}
const permit=(code:string)=>async(r:FastifyRequest,reply:FastifyReply)=>{await auth(r,reply);if(reply.sent)return;if(!hasPermission(r.session!,code))return reply.code(403).send({error:'forbidden',message:`缺少权限 ${code}`})}
const superAdmin=async(r:FastifyRequest,reply:FastifyReply)=>{await auth(r,reply);if(reply.sent)return;if(!r.session!.permissions.includes('*'))return reply.code(403).send({error:'super_admin_required',message:'仅超级管理员可以执行此操作'})}
async function audit(r:FastifyRequest,action:string,type:string,id?:string,details={}){await query(`INSERT INTO app.audit_logs(tenant_id,user_id,action,resource_type,resource_id,ip,details) VALUES($1,$2,$3,$4,$5,$6,$7)`,[r.session?.tenantId,r.session?.userId,action,type,id,r.ip,details])}
type Entitlements=Record<string,number|string[]>
async function currentEntitlements(tenantId:string){const row=(await query<{entitlements:Entitlements}>(`SELECT p.entitlements FROM app.subscriptions s JOIN app.plans p ON p.id=s.plan_id WHERE s.tenant_id=$1 AND s.status='active' AND s.period_end>now() ORDER BY s.created_at DESC LIMIT 1`,[tenantId])).rows[0];if(!row)throw Object.assign(new Error('租户没有有效订阅或订阅已到期'),{statusCode:402});return row.entitlements}
const quotaTables={providers:{table:'app.model_providers',where:'is_builtin=false',label:'模型供应商'},models:{table:'app.models',where:'true',label:'模型'},members:{table:'app.memberships',where:'true',label:'成员'}} as const
async function enforceResourceQuota(tenantId:string,key:keyof typeof quotaTables,additional=1){const quota=(await currentEntitlements(tenantId))[key],limit=typeof quota==='number'?quota:null;if(limit===null)return;const spec=quotaTables[key],used=(await query<{used:number}>(`SELECT count(*)::int used FROM ${spec.table} WHERE tenant_id=$1 AND ${spec.where}`,[tenantId])).rows[0].used;if(used+additional>limit)throw Object.assign(new Error(`当前套餐${spec.label}额度已用完（上限 ${limit}）`),{statusCode:429})}
async function enforceTenantMemberLimit(tenantId:string,additional=1){const row=(await query<{max_members:number|null;used:number}>(`SELECT t.max_members,(SELECT count(*)::int FROM app.memberships m WHERE m.tenant_id=t.id) used FROM app.tenants t WHERE t.id=$1`,[tenantId])).rows[0];if(row?.max_members&&row.used+additional>row.max_members)throw Object.assign(new Error(`租户成员上限为 ${row.max_members} 人`),{statusCode:429})}
async function enforceQuota(tenantId:string){const entitlements=await currentEntitlements(tenantId),quota=entitlements.api_calls;if(typeof quota!=='number')return;const row=(await query<{used:number}>(`SELECT coalesce(sum(u.api_calls),0)::int used FROM app.subscriptions s LEFT JOIN app.usage_events u ON u.tenant_id=s.tenant_id AND u.occurred_at BETWEEN s.period_start AND s.period_end WHERE s.tenant_id=$1 AND s.status='active' AND s.period_end>now()`,[tenantId])).rows[0];if(row.used>=quota)throw Object.assign(new Error('当前套餐 API 调用额度已用完'),{statusCode:429})}
async function resolveManagedTenant(session:Session,tenantId?:string){const target=tenantId??session.tenantId;if(target!==session.tenantId)assertPermission(session,'tenants:manage');if(!(await query(`SELECT 1 FROM app.tenants WHERE id=$1`,[target])).rowCount)throw Object.assign(new Error('租户不存在'),{statusCode:404});return target}
app.setErrorHandler((e,r,reply)=>{r.log.error(e);if(e instanceof z.ZodError)return reply.code(400).send({error:'validation_error',message:'输入数据不合法',details:e.issues});if((e as {code?:string}).code==='23505')return reply.code(409).send({error:'conflict',message:'名称或标识已存在'});const expected=e as Error&{statusCode?:number;publicCode?:string};if(expected.publicCode)return reply.code(expected.statusCode??400).send({error:expected.publicCode,message:expected.message});reply.code(expected.statusCode??500).send({error:'internal_error',message:config.production?'服务器内部错误':e instanceof Error?e.message:'未知错误'})})
app.get('/api/health',async()=>{await query('SELECT 1');const pong=await redis.ping();return ok({status:'ok',postgres:'ok',redis:pong})})
app.get('/api/auth/captcha',async(_r,reply)=>{reply.header('Cache-Control','no-store, no-cache, must-revalidate');return ok(await createCaptcha())})
app.post('/api/auth/login',async r=>{const body=z.object({email:z.string().trim().email(),password:userPassword,captchaId:z.string().uuid(),captchaCode:z.string().trim().min(1).max(12)}).parse(r.body);if(!await verifyCaptcha(body.captchaId,body.captchaCode))throw Object.assign(new Error('验证码错误或已过期，请刷新后重试'),{statusCode:400,publicCode:'captcha_invalid'});const row=(await query<LoginRow>(`SELECT u.id,u.email,u.name,u.password_hash,m.tenant_id,r.name role,r.permissions,t.status,t.valid_from,t.valid_until FROM app.users u JOIN app.memberships m ON m.user_id=u.id JOIN app.roles r ON r.id=m.role_id JOIN app.tenants t ON t.id=m.tenant_id WHERE lower(u.email)=lower($1) AND u.status='active' LIMIT 1`,[body.email])).rows[0];if(!row||!await verifyPassword(body.password,row.password_hash))throw Object.assign(new Error('邮箱或密码错误'),{statusCode:401});if(tenantUnavailable(row))throw Object.assign(new Error('租户已停用或不在有效期内'),{statusCode:403});const token=createSessionToken(),session:Session={userId:row.id,tenantId:row.tenant_id,email:row.email,name:row.name,role:row.role,permissions:row.permissions};await redis.set(`session:${sha256(token)}`,JSON.stringify(session),'EX',86400);await query(`UPDATE app.users SET last_login_at=now() WHERE id=$1`,[row.id]);return ok({token,user:session})})
app.post('/api/auth/logout',{preHandler:auth},async r=>{await redis.del(`session:${sha256(tokenOf(r)! )}`);return ok(true)})
app.get('/api/me',{preHandler:auth},async r=>{const t=(await query(`SELECT id,name,slug,description,locale,timezone,settings,status,valid_from,valid_until,created_at,updated_at,CASE WHEN brand_logo_path IS NULL THEN NULL ELSE '/api/tenant-brand/'||id||'/logo?updatedAt='||extract(epoch FROM updated_at)::bigint END brand_logo_url FROM app.tenants WHERE id=$1`,[r.session!.tenantId])).rows[0];return ok({user:r.session,tenant:t})})
app.get('/api/tenant-brand/:tenantId/logo',async(r,reply)=>{const tenantId=z.string().uuid().parse((r.params as {tenantId:string}).tenantId),logo=(await query<{brand_logo_path:string;brand_logo_mime_type:string}>(`SELECT brand_logo_path,brand_logo_mime_type FROM app.tenants WHERE id=$1 AND brand_logo_path IS NOT NULL`,[tenantId])).rows[0];if(!logo)throw Object.assign(new Error('企业 Logo 不存在'),{statusCode:404});reply.header('Cache-Control','public, max-age=3600').header('Content-Type',logo.brand_logo_mime_type);return reply.send(createReadStream(logo.brand_logo_path))})
const tenantSelect=`SELECT t.id,t.name,t.slug,t.description,t.locale,t.timezone,t.settings,t.status,t.valid_from,t.valid_until,t.max_members,t.created_at,t.updated_at,(CASE WHEN t.status<>'active' THEN t.status WHEN t.valid_from>now() THEN 'suspended' WHEN t.valid_until IS NOT NULL AND t.valid_until<=now() THEN 'expired' ELSE 'active' END) lifecycle_status,(SELECT count(*)::int FROM app.memberships m WHERE m.tenant_id=t.id) members,(SELECT count(*)::int FROM app.resource_categories c WHERE c.tenant_id=t.id AND c.resource_type='model') model_categories FROM app.tenants t`
const tenantCreateBody=z.object({name:z.string().min(2).max(100),slug:z.string().trim().regex(/^[a-z0-9][a-z0-9-]{1,78}[a-z0-9]$/).optional(),description:z.string().max(2000).default(''),locale:z.string().min(2).max(20).default('zh-CN'),timezone:z.string().min(2).max(50).default('Asia/Shanghai'),status:tenantStatus.default('active'),validFrom:tenantDate.optional(),validUntil:tenantDate.nullable().optional(),maxMembers:z.number().int().positive().nullable().optional(),settings:z.record(z.string(),z.boolean()).default({allow_api_keys:true,sync_models:true,failure_email:true}),owner:z.object({email:z.string().email(),name:z.string().min(2).max(100).optional(),password:userPassword.optional(),generatePassword:z.boolean().default(true)}).optional()}).superRefine((v,ctx)=>{const from=toTenantDate(v.validFrom)??new Date(),until=toTenantDate(v.validUntil);if(until&&until<=from)ctx.addIssue({code:'custom',message:'有效期结束时间必须晚于开始时间',path:['validUntil']})})
const tenantUpdateBody=z.object({name:z.string().min(2).max(100).optional(),slug:z.string().trim().regex(/^[a-z0-9][a-z0-9-]{1,78}[a-z0-9]$/).optional(),description:z.string().max(2000).optional(),locale:z.string().min(2).max(20).optional(),timezone:z.string().min(2).max(50).optional(),status:tenantStatus.optional(),validFrom:tenantDate.optional(),validUntil:tenantDate.nullable().optional(),maxMembers:z.number().int().positive().nullable().optional(),settings:z.record(z.string(),z.boolean()).optional()})
app.get('/api/tenants',{preHandler:auth},async r=>{const q=z.object({scope:z.enum(['current','all']).default('current'),status:tenantLifecycleStatus.optional(),search:z.string().trim().max(100).optional()}).parse(r.query),manageAll=q.scope==='all'&&hasPermission(r.session!,'tenants:manage'),search=q.search?`%${q.search}%`:null,params=manageAll?[q.status??null,search]:[r.session!.tenantId,q.status??null,search],where=manageAll?`($1::text IS NULL OR (CASE WHEN t.status<>'active' THEN t.status WHEN t.valid_from>now() THEN 'suspended' WHEN t.valid_until IS NOT NULL AND t.valid_until<=now() THEN 'expired' ELSE 'active' END)=$1) AND ($2::text IS NULL OR t.name ILIKE $2 OR t.slug ILIKE $2 OR t.description ILIKE $2)`: `t.id=$1 AND ($2::text IS NULL OR (CASE WHEN t.status<>'active' THEN t.status WHEN t.valid_from>now() THEN 'suspended' WHEN t.valid_until IS NOT NULL AND t.valid_until<=now() THEN 'expired' ELSE 'active' END)=$2) AND ($3::text IS NULL OR t.name ILIKE $3 OR t.slug ILIKE $3 OR t.description ILIKE $3)`;return ok((await query(`${tenantSelect} WHERE ${where} ORDER BY t.created_at DESC`,params)).rows)})
app.post('/api/tenants',{preHandler:permit('tenants:manage')},async r=>{const b=tenantCreateBody.parse(r.body),slug=b.slug??slugifyTenant(b.name),ownerPassword=b.owner?(b.owner.password??(b.owner.generatePassword?generateInitialPassword():undefined)):undefined,ownerPasswordHash=ownerPassword?await hashPassword(ownerPassword):undefined,temporary=ownerPasswordHash??await hashPassword(generateInitialPassword());const row=await transaction(async c=>{const created=(await c.query(`INSERT INTO app.tenants(name,slug,description,locale,timezone,settings,status,valid_from,valid_until,max_members) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) RETURNING id`,[b.name,slug,b.description,b.locale,b.timezone,JSON.stringify(b.settings),b.status,toTenantDate(b.validFrom)??new Date(),toTenantDate(b.validUntil),b.maxMembers??null])).rows[0] as {id:string};const ownerRoleId=await bootstrapTenantDefaults(c,created.id);if(b.owner){let user=(await c.query(`SELECT id FROM app.users WHERE lower(email)=lower($1)`,[b.owner.email])).rows[0] as {id:string}|undefined;if(!user)user=(await c.query(`INSERT INTO app.users(email,name,password_hash,status) VALUES($1,$2,$3,$4) RETURNING id`,[b.owner.email,b.owner.name??b.owner.email.split('@')[0],ownerPasswordHash??temporary,ownerPasswordHash?'active':'invited'])).rows[0] as {id:string};else if(ownerPasswordHash)await c.query(`UPDATE app.users SET password_hash=$1,status='active' WHERE id=$2`,[ownerPasswordHash,user.id]);await c.query(`INSERT INTO app.memberships(tenant_id,user_id,role_id) VALUES($1,$2,$3) ON CONFLICT(tenant_id,user_id) DO UPDATE SET role_id=EXCLUDED.role_id`,[created.id,user.id,ownerRoleId])}return created});const created=(await query(`${tenantSelect} WHERE t.id=$1`,[row.id])).rows[0];await audit(r,'tenant.create','tenant',row.id,{slug,ownerEmail:b.owner?.email,passwordSet:!!ownerPasswordHash});return ok(ownerPassword?{...created,initialPassword:{email:b.owner!.email,password:ownerPassword}}:created)})
app.patch('/api/tenants/:id',{preHandler:permit('tenants:manage')},async r=>{const id=z.string().uuid().parse((r.params as {id:string}).id),b=tenantUpdateBody.parse(r.body);if(b.validFrom!==undefined||b.validUntil!==undefined){const current=(await query<{valid_from:string;valid_until:string|null}>(`SELECT valid_from,valid_until FROM app.tenants WHERE id=$1`,[id])).rows[0];if(!current)throw Object.assign(new Error('租户不存在'),{statusCode:404});const from=b.validFrom?new Date(b.validFrom):new Date(current.valid_from),until=b.validUntil===undefined?toTenantDate(current.valid_until):toTenantDate(b.validUntil);if(until&&until<=from)throw Object.assign(new Error('有效期结束时间必须晚于开始时间'),{statusCode:400})}const updated=(await query(`WITH updated AS (UPDATE app.tenants SET name=coalesce($1,name),slug=coalesce($2,slug),description=coalesce($3,description),locale=coalesce($4,locale),timezone=coalesce($5,timezone),settings=coalesce($6,settings),status=coalesce($7,status),valid_from=coalesce($8,valid_from),valid_until=CASE WHEN $9::boolean THEN $10 ELSE valid_until END,max_members=CASE WHEN $11::boolean THEN $12 ELSE max_members END,updated_at=now() WHERE id=$13 RETURNING id) ${tenantSelect} JOIN updated u ON u.id=t.id`,[b.name,b.slug,b.description,b.locale,b.timezone,b.settings?JSON.stringify(b.settings):null,b.status,b.validFrom?new Date(b.validFrom):null,b.validUntil!==undefined,b.validUntil?new Date(b.validUntil):null,b.maxMembers!==undefined,b.maxMembers??null,id])).rows[0];if(!updated)throw Object.assign(new Error('租户不存在'),{statusCode:404});await audit(r,'tenant.update','tenant',id,b);return ok(updated)})
app.delete('/api/tenants/:id',{preHandler:permit('tenants:manage')},async r=>{const id=z.string().uuid().parse((r.params as {id:string}).id);if(id===r.session!.tenantId)throw Object.assign(new Error('不能删除当前登录租户'),{statusCode:400});const row=(await query(`DELETE FROM app.tenants WHERE id=$1 RETURNING id`,[id])).rows[0];if(!row)throw Object.assign(new Error('租户不存在'),{statusCode:404});await audit(r,'tenant.delete','tenant',id);return ok(true)})

const categoryResourceType=z.literal('model')
const categoryColor=z.string().regex(/^#[0-9a-fA-F]{6}$/,'分类颜色格式不合法')
app.get('/api/categories',{preHandler:permit('models:read')},async r=>{categoryResourceType.parse((r.query as {resourceType?:string}).resourceType);return ok((await query(`SELECT c.id,c.name,c.color,c.description,c.sort_order,c.resource_type,count(a.resource_id)::int usage_count FROM app.resource_categories c LEFT JOIN app.resource_category_assignments a ON a.category_id=c.id AND a.tenant_id=c.tenant_id WHERE c.tenant_id=$1 AND c.resource_type='model' GROUP BY c.id ORDER BY c.sort_order,c.name`,[r.session!.tenantId])).rows)})
app.post('/api/categories',{preHandler:permit('models:write')},async r=>{const b=z.object({resourceType:categoryResourceType,name:z.string().trim().min(1).max(80),color:categoryColor.default('#6366f1'),description:z.string().max(1000).default('')}).parse(r.body),row=(await query(`INSERT INTO app.resource_categories(tenant_id,resource_type,name,color,description) VALUES($1,$2,$3,$4,$5) RETURNING *`,[r.session!.tenantId,b.resourceType,b.name,b.color,b.description])).rows[0];await audit(r,'category.create','category',row.id);return ok(row)})
app.patch('/api/categories/:id',{preHandler:permit('models:write')},async r=>{const id=z.string().uuid().parse((r.params as {id:string}).id),b=z.object({name:z.string().trim().min(1).max(80).optional(),color:categoryColor.optional(),description:z.string().max(1000).optional()}).parse(r.body),row=(await query(`UPDATE app.resource_categories SET name=coalesce($1,name),color=coalesce($2,color),description=coalesce($3,description) WHERE id=$4 AND tenant_id=$5 AND resource_type='model' RETURNING *`,[b.name,b.color,b.description,id,r.session!.tenantId])).rows[0];if(!row)throw Object.assign(new Error('模型分类不存在'),{statusCode:404});await audit(r,'category.update','category',id);return ok(row)})
app.delete('/api/categories/:id',{preHandler:permit('models:write')},async r=>{const id=z.string().uuid().parse((r.params as {id:string}).id),row=(await query(`DELETE FROM app.resource_categories WHERE id=$1 AND tenant_id=$2 AND resource_type='model' RETURNING id`,[id,r.session!.tenantId])).rows[0];if(!row)throw Object.assign(new Error('模型分类不存在'),{statusCode:404});await audit(r,'category.delete','category',id);return ok(true)})
app.put('/api/category-assignments',{preHandler:permit('models:write')},async r=>{const b=z.object({resourceType:categoryResourceType,resourceId:z.string().uuid(),categoryIds:z.array(z.string().uuid()).max(100).transform(ids=>[...new Set(ids)])}).parse(r.body),t=r.session!.tenantId;await transaction(async c=>{if(!(await c.query(`SELECT 1 FROM app.models WHERE id=$1 AND tenant_id=$2`,[b.resourceId,t])).rowCount)throw Object.assign(new Error('模型不存在'),{statusCode:404});if(b.categoryIds.length){const count=(await c.query<{count:number}>(`SELECT count(*)::int count FROM app.resource_categories WHERE tenant_id=$1 AND resource_type='model' AND id=ANY($2::uuid[])`,[t,b.categoryIds])).rows[0].count;if(count!==b.categoryIds.length)throw Object.assign(new Error('分类列表包含不存在或无权访问的分类'),{statusCode:400})}await c.query(`DELETE FROM app.resource_category_assignments WHERE tenant_id=$1 AND resource_type='model' AND resource_id=$2`,[t,b.resourceId]);for(const categoryId of b.categoryIds)await c.query(`INSERT INTO app.resource_category_assignments(tenant_id,category_id,resource_type,resource_id) VALUES($1,$2,'model',$3)`,[t,categoryId,b.resourceId])});await audit(r,'category.assign','model',b.resourceId,{categoryIds:b.categoryIds});return ok(true)})

app.get('/api/providers',{preHandler:permit('models:read')},async r=>ok((await query(`SELECT p.id,p.code,p.name,p.base_url,p.provider_type,p.protocol,p.auth_type,p.status,p.is_builtin,p.last_synced_at,count(m.id)::int models,(p.status='connected' AND count(m.id) FILTER(WHERE m.enabled)>0) available FROM app.model_providers p LEFT JOIN app.models m ON m.provider_id=p.id WHERE p.tenant_id=$1 GROUP BY p.id ORDER BY p.is_builtin DESC,p.provider_type,p.name`,[r.session!.tenantId])).rows))
const providerBody=z.object({name:z.string().trim().min(2).max(100),code:z.string().max(60).regex(/^[a-z][a-z0-9_-]+$/).optional(),baseUrl:z.string().url(),providerType:z.enum(['official','relay','local','custom']),protocol:z.enum(['openai','anthropic','ollama','custom']),authType:z.enum(['bearer','x-api-key','none'])})
function generateProviderCode(name:string){const slug=name.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,47).replace(/-$/,'')||'custom';return `${slug}-${randomUUID().slice(0,8)}`}
app.post('/api/providers',{preHandler:permit('models:write')},async r=>{const b=providerBody.extend({authType:z.enum(['bearer','x-api-key','none']).default('bearer')}).parse(r.body),t=r.session!.tenantId;await enforceResourceQuota(t,'providers');const code=b.code??generateProviderCode(b.name);const row=(await query(`INSERT INTO app.model_providers(tenant_id,code,name,base_url,provider_type,protocol,auth_type) VALUES($1,$2,$3,$4,$5,$6,$7) RETURNING id,code,name,base_url,provider_type,protocol,auth_type,status,is_builtin`,[t,code,b.name,b.baseUrl,b.providerType,b.protocol,b.authType])).rows[0];await audit(r,'provider.create','provider',row.id,{protocol:b.protocol});return ok(row)})
app.patch('/api/providers/:id',{preHandler:permit('models:write')},async r=>{const b=providerBody.partial().extend({status:z.enum(['paused','connected']).optional()}).parse(r.body),id=(r.params as {id:string}).id,t=r.session!.tenantId,current=(await query(`SELECT status,auth_type,encrypted_api_key FROM app.model_providers WHERE id=$1 AND tenant_id=$2`,[id,t])).rows[0];if(!current)throw Object.assign(new Error('供应商不存在'),{statusCode:404});if(b.status==='connected'&&current.status!=='paused')throw Object.assign(new Error('只有已暂停的供应商可以恢复'),{statusCode:409});if(b.status==='connected'&&(b.authType??current.auth_type)!=='none'&&!current.encrypted_api_key)throw Object.assign(new Error('供应商尚未配置 API Key，请先测试连接'),{statusCode:409});const connectionChanged=b.baseUrl!==undefined||b.protocol!==undefined||b.authType!==undefined,status=b.status??(connectionChanged?'disconnected':undefined);const row=(await query(`UPDATE app.model_providers SET name=coalesce($1,name),base_url=coalesce($2,base_url),provider_type=coalesce($3,provider_type),protocol=coalesce($4,protocol),auth_type=coalesce($5,auth_type),status=coalesce($6,status) WHERE id=$7 AND tenant_id=$8 RETURNING id,code,name,base_url,provider_type,protocol,auth_type,status,is_builtin,last_synced_at`,[b.name,b.baseUrl,b.providerType,b.protocol,b.authType,status,id,t])).rows[0];await audit(r,b.status==='paused'?'provider.pause':b.status==='connected'?'provider.resume':'provider.update','provider',id,{name:b.name,providerType:b.providerType,protocol:b.protocol,authType:b.authType,status:b.status,connectionChanged});return ok(row)})
app.delete('/api/providers/:id',{preHandler:permit('models:write')},async r=>{const id=z.string().uuid().parse((r.params as {id:string}).id),t=r.session!.tenantId,provider=(await query(`SELECT is_builtin FROM app.model_providers WHERE id=$1 AND tenant_id=$2`,[id,t])).rows[0];if(!provider)throw Object.assign(new Error('供应商不存在'),{statusCode:404});if(provider.is_builtin)throw Object.assign(new Error('内置供应商不能删除'),{statusCode:400});await query(`DELETE FROM app.model_providers WHERE id=$1 AND tenant_id=$2`,[id,t]);await audit(r,'provider.delete','provider',id);return ok(true)})
app.post('/api/providers/:id/connect',{preHandler:permit('models:write')},async r=>{const b=z.object({apiKey:z.string().max(10000).default(''),baseUrl:z.string().url().optional(),manualModels:z.array(z.string().min(1).max(150)).max(200).default([])}).parse(r.body),id=(r.params as {id:string}).id,t=r.session!.tenantId;const stored=(await query(`SELECT * FROM app.model_providers WHERE id=$1 AND tenant_id=$2`,[id,t])).rows[0] as ProviderRecord|undefined;if(!stored)throw Object.assign(new Error('供应商不存在'),{statusCode:404});const p={...stored,base_url:b.baseUrl??stored.base_url},key=b.apiKey||(stored.encrypted_api_key?decrypt(stored.encrypted_api_key):undefined);if(p.auth_type!=='none'&&!key)throw Object.assign(new Error('该服务需要 API Key'),{statusCode:400});await query(`UPDATE app.model_providers SET status='testing' WHERE id=$1 AND tenant_id=$2`,[id,t]);try{const found=b.manualModels.length?b.manualModels.map(x=>({id:x,name:x})):await discoverProviderModels(p,key);const synced=await saveProviderModels(t,id,found);const saved=(await query(`UPDATE app.model_providers SET encrypted_api_key=CASE WHEN $1='' THEN encrypted_api_key ELSE $2 END,base_url=$3,status='connected',last_synced_at=now() WHERE id=$4 AND tenant_id=$5 RETURNING *`,[b.apiKey,b.apiKey?encrypt(b.apiKey):null,p.base_url,id,t])).rows[0];await audit(r,'provider.connect','provider',id,{models:synced,protocol:p.protocol});return ok({provider:{...saved,encrypted_api_key:undefined},synced})}catch(e){await query(`UPDATE app.model_providers SET status='error' WHERE id=$1 AND tenant_id=$2`,[id,t]);throw e}})
app.delete('/api/providers/:id/connect',{preHandler:permit('models:write')},async r=>ok((await query(`UPDATE app.model_providers SET encrypted_api_key=null,status='disconnected' WHERE id=$1 AND tenant_id=$2 RETURNING id`,[(r.params as {id:string}).id,r.session!.tenantId])).rows[0]))
app.get('/api/models',{preHandler:permit('models:read')},async r=>{const q=r.query as Record<string,string|undefined>,categoryId=z.string().uuid().optional().parse(q.categoryId),providerId=z.string().uuid().optional().parse(q.providerId),modelCategory=z.enum(modelCategories).optional().parse(q.modelCategory),availability=z.enum(['all','available','disabled']).default('all').parse(q.availability),search=z.string().trim().max(150).default('').parse(q.search);return ok((await query(`SELECT m.*,p.name provider,p.status provider_status,(m.enabled AND p.status='connected') available,coalesce((SELECT json_agg(json_build_object('id',c.id,'name',c.name,'color',c.color) ORDER BY c.sort_order,c.name) FROM app.resource_category_assignments a JOIN app.resource_categories c ON c.id=a.category_id WHERE a.tenant_id=m.tenant_id AND a.resource_type='model' AND a.resource_id=m.id),'[]') categories FROM app.models m JOIN app.model_providers p ON p.id=m.provider_id WHERE m.tenant_id=$1 AND ($2::uuid IS NULL OR EXISTS(SELECT 1 FROM app.resource_category_assignments x WHERE x.tenant_id=m.tenant_id AND x.resource_type='model' AND x.resource_id=m.id AND x.category_id=$2)) AND ($3::uuid IS NULL OR m.provider_id=$3) AND ($4::varchar IS NULL OR m.model_category=$4) AND ($5='all' OR ($5='available' AND m.enabled=true AND p.status='connected') OR ($5='disabled' AND (m.enabled=false OR p.status<>'connected'))) AND ($6='' OR m.name ILIKE '%'||$6||'%' OR m.external_id ILIKE '%'||$6||'%' OR p.name ILIKE '%'||$6||'%') ORDER BY p.name,m.name`,[r.session!.tenantId,categoryId??null,providerId??null,modelCategory??null,availability,search])).rows)})
const modelBody=z.object({externalId:z.string().trim().min(1).max(150),name:z.string().trim().min(1).max(150),modelCategory:z.enum(modelCategories).default('language'),contextWindow:z.number().int().min(0).max(10000000).default(131072),inputPrice:z.number().min(0).max(1000000).default(0),outputPrice:z.number().min(0).max(1000000).default(0),enabled:z.boolean().default(true)})
app.post('/api/providers/:providerId/models',{preHandler:permit('models:write')},async r=>{const providerId=z.string().uuid().parse((r.params as {providerId:string}).providerId),b=modelBody.parse(r.body),t=r.session!.tenantId;if(!(await query(`SELECT 1 FROM app.model_providers WHERE id=$1 AND tenant_id=$2`,[providerId,t])).rowCount)throw Object.assign(new Error('供应商不存在'),{statusCode:404});await enforceResourceQuota(t,'models');const row=(await query(`INSERT INTO app.models(tenant_id,provider_id,external_id,name,model_category,context_window,input_price,output_price,enabled) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9) RETURNING *`,[t,providerId,b.externalId,b.name,b.modelCategory,b.contextWindow,b.inputPrice,b.outputPrice,b.enabled])).rows[0];await audit(r,'model.create','model',row.id,{providerId,externalId:b.externalId,modelCategory:b.modelCategory});return ok(row)})
app.patch('/api/models/:id',{preHandler:permit('models:write')},async r=>{const id=z.string().uuid().parse((r.params as {id:string}).id),b=modelBody.partial().parse(r.body),t=r.session!.tenantId;const row=(await query(`UPDATE app.models SET external_id=coalesce($1,external_id),name=coalesce($2,name),model_category=coalesce($3,model_category),context_window=coalesce($4,context_window),input_price=coalesce($5,input_price),output_price=coalesce($6,output_price),enabled=coalesce($7,enabled) WHERE id=$8 AND tenant_id=$9 RETURNING *`,[b.externalId,b.name,b.modelCategory,b.contextWindow,b.inputPrice,b.outputPrice,b.enabled,id,t])).rows[0];if(!row)throw Object.assign(new Error('模型不存在'),{statusCode:404});await audit(r,'model.update','model',id,b);return ok(row)})
app.patch('/api/models/batch',{preHandler:permit('models:write')},async r=>{const b=z.object({ids:z.array(z.string().uuid()).min(1).max(500).transform(ids=>[...new Set(ids)]),modelCategory:z.enum(modelCategories).optional(),contextWindow:z.number().int().min(0).max(10000000).optional(),inputPrice:z.number().min(0).max(1000000).optional(),outputPrice:z.number().min(0).max(1000000).optional(),enabled:z.boolean().optional()}).refine(value=>value.modelCategory!==undefined||value.contextWindow!==undefined||value.inputPrice!==undefined||value.outputPrice!==undefined||value.enabled!==undefined,{message:'至少选择一个批量配置项'}).parse(r.body),t=r.session!.tenantId;const updated=await transaction(async c=>{const count=(await c.query<{count:number}>(`SELECT count(*)::int count FROM app.models WHERE tenant_id=$1 AND id=ANY($2::uuid[])`,[t,b.ids])).rows[0].count;if(count!==b.ids.length)throw Object.assign(new Error('批量选择包含不存在或无权访问的模型'),{statusCode:404});return (await c.query(`UPDATE app.models SET model_category=coalesce($1,model_category),context_window=coalesce($2,context_window),input_price=coalesce($3,input_price),output_price=coalesce($4,output_price),enabled=coalesce($5,enabled) WHERE tenant_id=$6 AND id=ANY($7::uuid[])`,[b.modelCategory,b.contextWindow,b.inputPrice,b.outputPrice,b.enabled,t,b.ids])).rowCount??0});await audit(r,'model.batch_update','model',undefined,{count:updated,modelCategory:b.modelCategory,contextWindow:b.contextWindow,inputPrice:b.inputPrice,outputPrice:b.outputPrice,enabled:b.enabled});return ok({updated})})
app.delete('/api/models/:id',{preHandler:permit('models:write')},async r=>{const id=z.string().uuid().parse((r.params as {id:string}).id),t=r.session!.tenantId;if(!(await query(`SELECT 1 FROM app.models WHERE id=$1 AND tenant_id=$2`,[id,t])).rowCount)throw Object.assign(new Error('模型不存在'),{statusCode:404});await transaction(async c=>{await c.query(`DELETE FROM app.resource_category_assignments WHERE tenant_id=$1 AND resource_type='model' AND resource_id=$2`,[t,id]);await c.query(`DELETE FROM app.models WHERE id=$1 AND tenant_id=$2`,[id,t])});await audit(r,'model.delete','model',id);return ok(true)})

app.get('/api/api-keys',{preHandler:permit('apikeys:manage')},async r=>{const tenantId=await resolveManagedTenant(r.session!,z.string().uuid().optional().parse((r.query as {tenantId?:string}).tenantId));return ok((await query(`SELECT k.id,k.tenant_id,t.name tenant_name,k.name,k.key_prefix,k.scopes,k.last_used_at,k.expires_at,k.created_at FROM app.api_keys k JOIN app.tenants t ON t.id=k.tenant_id WHERE k.tenant_id=$1 AND k.revoked_at IS NULL ORDER BY k.created_at DESC`,[tenantId])).rows)})
app.post('/api/api-keys',{preHandler:permit('apikeys:manage')},async r=>{const b=z.object({name:z.string().min(2),scopes:z.array(z.string()).default(['*']),expiresAt:z.string().datetime().nullable().default(null),tenantId:z.string().uuid().optional()}).parse(r.body),tenantId=await resolveManagedTenant(r.session!,b.tenantId),key=createApiKey();const row=(await query(`WITH created AS (INSERT INTO app.api_keys(tenant_id,user_id,name,key_prefix,key_hash,scopes,expires_at) VALUES($1,$2,$3,$4,$5,$6,$7) RETURNING id,tenant_id,name,key_prefix,scopes,expires_at,created_at) SELECT c.*,t.name tenant_name FROM created c JOIN app.tenants t ON t.id=c.tenant_id`,[tenantId,r.session!.userId,b.name,key.prefix,key.hash,JSON.stringify(b.scopes),b.expiresAt])).rows[0];await audit(r,'apikey.create','api_key',row.id,{tenantId});return ok({...row,key:key.raw})})
app.get('/api/api-keys/:id',{preHandler:permit('apikeys:manage')},async r=>{const id=z.string().uuid().parse((r.params as {id:string}).id),tenantId=await resolveManagedTenant(r.session!,z.string().uuid().optional().parse((r.query as {tenantId?:string}).tenantId)),row=(await query(`SELECT k.id,k.tenant_id,t.name tenant_name,k.name,k.key_prefix,k.scopes,k.last_used_at,k.expires_at,k.created_at FROM app.api_keys k JOIN app.tenants t ON t.id=k.tenant_id WHERE k.id=$1 AND k.tenant_id=$2 AND k.revoked_at IS NULL`,[id,tenantId])).rows[0];if(!row)throw Object.assign(new Error('API Key 不存在'),{statusCode:404});return ok(row)})
app.patch('/api/api-keys/:id',{preHandler:permit('apikeys:manage')},async r=>{const id=z.string().uuid().parse((r.params as {id:string}).id),b=z.object({sourceTenantId:z.string().uuid().optional(),tenantId:z.string().uuid().optional(),name:z.string().min(2).max(100),scopes:z.array(z.string().min(1).max(100)).min(1).max(100),expiresAt:z.string().datetime().nullable()}).parse(r.body),sourceTenantId=await resolveManagedTenant(r.session!,b.sourceTenantId),tenantId=await resolveManagedTenant(r.session!,b.tenantId),row=(await query(`WITH updated AS (UPDATE app.api_keys SET tenant_id=$1,name=$2,scopes=$3,expires_at=$4 WHERE id=$5 AND tenant_id=$6 AND revoked_at IS NULL RETURNING id,tenant_id,name,key_prefix,scopes,last_used_at,expires_at,created_at) SELECT u.*,t.name tenant_name FROM updated u JOIN app.tenants t ON t.id=u.tenant_id`,[tenantId,b.name,JSON.stringify([...new Set(b.scopes)]),b.expiresAt,id,sourceTenantId])).rows[0];if(!row)throw Object.assign(new Error('API Key 不存在'),{statusCode:404});await audit(r,'apikey.update','api_key',id,{sourceTenantId,tenantId,scopes:row.scopes,expiresAt:b.expiresAt});return ok(row)})
app.delete('/api/api-keys/:id',{preHandler:permit('apikeys:manage')},async r=>{const tenantId=await resolveManagedTenant(r.session!,z.string().uuid().optional().parse((r.query as {tenantId?:string}).tenantId)),id=z.string().uuid().parse((r.params as {id:string}).id),row=(await query(`UPDATE app.api_keys SET revoked_at=now() WHERE id=$1 AND tenant_id=$2 AND revoked_at IS NULL RETURNING id`,[id,tenantId])).rows[0];if(!row)throw Object.assign(new Error('API Key 不存在'),{statusCode:404});await audit(r,'apikey.delete','api_key',id,{tenantId});return ok(true)})

app.get('/api/members',{preHandler:permit('members:manage')},async r=>{const tenantId=await resolveManagedTenant(r.session!,z.string().uuid().optional().parse((r.query as {tenantId?:string}).tenantId));return ok((await query(`SELECT u.id,u.name,u.email,u.status,u.last_login_at,u.created_at,m.joined_at,r.name role,r.id role_id FROM app.memberships m JOIN app.users u ON u.id=m.user_id JOIN app.roles r ON r.id=m.role_id WHERE m.tenant_id=$1 ORDER BY m.joined_at`,[tenantId])).rows)})
app.post('/api/members/invite',{preHandler:permit('members:manage')},async r=>{const b=z.object({email:z.string().email(),name:z.string().min(2).optional(),roleId:z.string().uuid(),tenantId:z.string().uuid().optional(),password:userPassword.optional(),generatePassword:z.boolean().default(true)}).parse(r.body),t=await resolveManagedTenant(r.session!,b.tenantId),role=(await query(`SELECT 1 FROM app.roles WHERE id=$1 AND tenant_id=$2`,[b.roleId,t])).rowCount;if(!role)throw Object.assign(new Error('角色不存在或不属于目标租户'),{statusCode:400});const existing=(await query(`SELECT 1 FROM app.memberships m JOIN app.users u ON u.id=m.user_id WHERE m.tenant_id=$1 AND lower(u.email)=lower($2)`,[t,b.email])).rowCount;if(!existing){await enforceResourceQuota(t,'members');await enforceTenantMemberLimit(t)}const initialPassword=b.password??(b.generatePassword?generateInitialPassword():undefined),passwordHash=initialPassword?await hashPassword(initialPassword):undefined,temporary=passwordHash??await hashPassword(generateInitialPassword());const row=await transaction(async c=>{let user=(await c.query(`SELECT id,email,name,status FROM app.users WHERE lower(email)=lower($1)`,[b.email])).rows[0];if(!user)user=(await c.query(`INSERT INTO app.users(email,name,password_hash,status) VALUES($1,$2,$3,$4) RETURNING id,email,name,status`,[b.email,b.name??b.email.split('@')[0],passwordHash??temporary,passwordHash?'active':'invited'])).rows[0];else if(passwordHash)user=(await c.query(`UPDATE app.users SET password_hash=$1,status='active' WHERE id=$2 RETURNING id,email,name,status`,[passwordHash,user.id])).rows[0];await c.query(`INSERT INTO app.memberships(tenant_id,user_id,role_id) VALUES($1,$2,$3) ON CONFLICT(tenant_id,user_id) DO UPDATE SET role_id=EXCLUDED.role_id`,[t,user.id,b.roleId]);return user});await audit(r,'member.invite','user',row.id,{email:b.email,tenantId:t,passwordSet:!!passwordHash});return ok(initialPassword?{...row,initialPassword:{email:row.email,password:initialPassword}}:row)})
app.post('/api/members/:id/password',{preHandler:permit('members:manage')},async r=>{const userId=z.string().uuid().parse((r.params as {id:string}).id),b=z.object({tenantId:z.string().uuid().optional(),password:userPassword.optional(),generatePassword:z.boolean().default(true)}).parse(r.body),t=await resolveManagedTenant(r.session!,b.tenantId),initialPassword=b.password??(b.generatePassword?generateInitialPassword():undefined);if(!initialPassword)throw Object.assign(new Error('请填写新密码或启用自动生成密码'),{statusCode:400});const member=(await query<{email:string}>(`SELECT u.email FROM app.memberships m JOIN app.users u ON u.id=m.user_id WHERE m.tenant_id=$1 AND u.id=$2`,[t,userId])).rows[0];if(!member)throw Object.assign(new Error('成员不存在'),{statusCode:404});await query(`UPDATE app.users SET password_hash=$1,status='active' WHERE id=$2`,[await hashPassword(initialPassword),userId]);await audit(r,'member.password.reset','user',userId,{tenantId:t,email:member.email});return ok({userId,email:member.email,password:initialPassword})})
app.patch('/api/members/:id',{preHandler:permit('members:manage')},async r=>{const userId=z.string().uuid().parse((r.params as {id:string}).id),b=z.object({tenantId:z.string().uuid().optional(),roleId:z.string().uuid().optional(),status:z.enum(['active','invited','disabled']).optional()}).parse(r.body),t=await resolveManagedTenant(r.session!,b.tenantId);if(userId===r.session!.userId&&b.status==='disabled')throw Object.assign(new Error('不能禁用当前登录账号'),{statusCode:400});if(b.roleId&&!(await query(`SELECT 1 FROM app.roles WHERE id=$1 AND tenant_id=$2`,[b.roleId,t])).rowCount)throw Object.assign(new Error('角色不存在或不属于目标租户'),{statusCode:400});const row=await transaction(async c=>{if(b.status)await c.query(`UPDATE app.users SET status=$1 WHERE id=$2`,[b.status,userId]);if(b.roleId)await c.query(`UPDATE app.memberships SET role_id=$1 WHERE tenant_id=$2 AND user_id=$3`,[b.roleId,t,userId]);return (await c.query(`SELECT u.id,u.name,u.email,u.status,u.last_login_at,u.created_at,m.joined_at,r.name role,r.id role_id FROM app.memberships m JOIN app.users u ON u.id=m.user_id JOIN app.roles r ON r.id=m.role_id WHERE m.tenant_id=$1 AND u.id=$2`,[t,userId])).rows[0]});if(!row)throw Object.assign(new Error('成员不存在'),{statusCode:404});await audit(r,'member.update','user',userId,{tenantId:t,roleId:b.roleId,status:b.status});return ok(row)})
app.delete('/api/members/:id',{preHandler:permit('members:manage')},async r=>{const userId=z.string().uuid().parse((r.params as {id:string}).id),q=z.object({tenantId:z.string().uuid().optional()}).parse(r.query),t=await resolveManagedTenant(r.session!,q.tenantId);if(userId===r.session!.userId&&t===r.session!.tenantId)throw Object.assign(new Error('不能移除当前登录账号'),{statusCode:400});const row=(await query(`DELETE FROM app.memberships WHERE tenant_id=$1 AND user_id=$2 RETURNING user_id`,[t,userId])).rows[0];if(!row)throw Object.assign(new Error('成员不存在'),{statusCode:404});await audit(r,'member.remove','user',userId,{tenantId:t});return ok(true)})
app.get('/api/roles',{preHandler:permit('members:manage')},async r=>{const tenantId=await resolveManagedTenant(r.session!,z.string().uuid().optional().parse((r.query as {tenantId?:string}).tenantId));return ok((await query(`SELECT * FROM app.roles WHERE tenant_id=$1 ORDER BY is_system DESC,name`,[tenantId])).rows)})
app.post('/api/roles',{preHandler:permit('members:manage')},async r=>{const b=z.object({tenantId:z.string().uuid().optional(),name:z.string().min(2),description:z.string().default(''),permissions:z.array(z.string()).max(100)}).parse(r.body),tenantId=await resolveManagedTenant(r.session!,b.tenantId),permissions=await validateRolePermissions(r.session!,b.permissions);const row=(await query(`INSERT INTO app.roles(tenant_id,name,description,permissions) VALUES($1,$2,$3,$4) RETURNING *`,[tenantId,b.name,b.description,JSON.stringify(permissions)])).rows[0];await audit(r,'role.create','role',row.id,{tenantId});return ok(row)})
app.patch('/api/roles/:id',{preHandler:permit('members:manage')},async r=>{const id=z.string().uuid().parse((r.params as {id:string}).id),b=z.object({tenantId:z.string().uuid().optional(),name:z.string().min(2).optional(),description:z.string().optional(),permissions:z.array(z.string()).max(100).optional()}).parse(r.body),tenantId=await resolveManagedTenant(r.session!,b.tenantId),current=(await query<{name:string;is_system:boolean;permissions:string[]}>(`SELECT name,is_system,permissions FROM app.roles WHERE id=$1 AND tenant_id=$2`,[id,tenantId])).rows[0];if(!current)throw Object.assign(new Error('角色不存在'),{statusCode:404});if(current.permissions.includes('*'))throw Object.assign(new Error('平台所有者角色不可修改'),{statusCode:403});if(current.is_system&&b.name!==undefined&&b.name!==current.name)throw Object.assign(new Error('系统角色名称不可修改'),{statusCode:400});const permissions=b.permissions?await validateRolePermissions(r.session!,b.permissions):undefined,row=(await query(`UPDATE app.roles SET name=coalesce($1,name),description=coalesce($2,description),permissions=coalesce($3,permissions) WHERE id=$4 AND tenant_id=$5 RETURNING *`,[current.is_system?null:b.name,b.description,permissions?JSON.stringify(permissions):null,id,tenantId])).rows[0];await audit(r,'role.update','role',id,{tenantId,systemRole:current.is_system});return ok(row)})
app.get('/api/dictionaries',{preHandler:permit('dictionaries:manage')},async r=>ok((await query(`SELECT d.*,coalesce(json_agg(json_build_object('id',i.id,'label',i.label,'value',i.value,'color',i.color,'sortOrder',i.sort_order,'enabled',i.enabled) ORDER BY i.sort_order) FILTER(WHERE i.id IS NOT NULL),'[]') items FROM app.dictionaries d LEFT JOIN app.dictionary_items i ON i.dictionary_id=d.id WHERE d.tenant_id=$1 GROUP BY d.id ORDER BY d.name`,[r.session!.tenantId])).rows))
app.post('/api/dictionaries',{preHandler:permit('dictionaries:manage')},async r=>{const b=z.object({code:z.string().regex(/^[a-z][a-z0-9_]+$/),name:z.string().min(2),description:z.string().default('')}).parse(r.body);return ok((await query(`INSERT INTO app.dictionaries(tenant_id,code,name,description) VALUES($1,$2,$3,$4) RETURNING *`,[r.session!.tenantId,b.code,b.name,b.description])).rows[0])})
app.post('/api/dictionaries/:id/items',{preHandler:permit('dictionaries:manage')},async r=>{const b=z.object({label:z.string().min(1),value:z.string().min(1),color:z.string().default('#64748b')}).parse(r.body);return ok((await query(`INSERT INTO app.dictionary_items(tenant_id,dictionary_id,label,value,color) VALUES($1,$2,$3,$4,$5) RETURNING *`,[r.session!.tenantId,(r.params as {id:string}).id,b.label,b.value,b.color])).rows[0])})
app.patch('/api/dictionary-items/:id',{preHandler:permit('dictionaries:manage')},async r=>{const id=z.string().uuid().parse((r.params as {id:string}).id),b=z.object({enabled:z.boolean()}).parse(r.body),row=(await query(`UPDATE app.dictionary_items SET enabled=$1 WHERE id=$2 AND tenant_id=$3 RETURNING id,label,value,color,sort_order,enabled`,[b.enabled,id,r.session!.tenantId])).rows[0];if(!row)throw Object.assign(new Error('字典项不存在'),{statusCode:404});await audit(r,'dictionary.item.update','dictionary_item',id,{enabled:b.enabled});return ok(row)})
app.get('/api/billing',{preHandler:permit('plans:manage')},async r=>ok({subscription:(await query(`SELECT s.*,p.name,p.price_cny,p.price_usd,p.billing_period,p.entitlements FROM app.subscriptions s JOIN app.plans p ON p.id=s.plan_id WHERE s.tenant_id=$1 AND s.status='active' AND s.period_end>now() ORDER BY s.created_at DESC LIMIT 1`,[r.session!.tenantId])).rows[0],plans:(await query(`SELECT p.*,EXISTS(SELECT 1 FROM app.payment_orders o WHERE o.tenant_id=$1 AND o.plan_id=p.id AND o.status='paid') purchased FROM app.plans p WHERE p.active=true ORDER BY p.price_cny`,[r.session!.tenantId])).rows,orders:(await query(`SELECT * FROM app.payment_orders WHERE tenant_id=$1 ORDER BY created_at DESC`,[r.session!.tenantId])).rows,isSuperAdmin:r.session!.permissions.includes('*')}))
app.post('/api/billing/switch-plan',{preHandler:superAdmin},async r=>{const b=z.object({planId:z.string().uuid()}).parse(r.body),plan=(await query<{id:string;billing_period:string}>(`SELECT id,billing_period FROM app.plans WHERE id=$1 AND active=true`,[b.planId])).rows[0];if(!plan)throw Object.assign(new Error('套餐不存在或已停用'),{statusCode:404});const period=plan.billing_period==='year'?'1 year':'1 month',subscription=await transaction(async c=>{await c.query(`SELECT id FROM app.tenants WHERE id=$1 FOR UPDATE`,[r.session!.tenantId]);await c.query(`UPDATE app.subscriptions SET status='cancelled' WHERE tenant_id=$1 AND status='active'`,[r.session!.tenantId]);return (await c.query(`INSERT INTO app.subscriptions(tenant_id,plan_id,provider,provider_ref,status,period_start,period_end) VALUES($1,$2,'manual',$3,'active',now(),now()+$4::interval) RETURNING *`,[r.session!.tenantId,plan.id,`super-admin:${r.session!.userId}`,period])).rows[0]});await audit(r,'subscription.plan.switch','subscription',subscription.id,{planId:plan.id,method:'super_admin_manual'});return ok(subscription)})
app.post('/api/billing/activate-paid-plan',{preHandler:permit('plans:manage')},async r=>{const b=z.object({planId:z.string().uuid()}).parse(r.body),subscription=await transaction(async c=>{await c.query(`SELECT id FROM app.tenants WHERE id=$1 FOR UPDATE`,[r.session!.tenantId]);const current=(await c.query<{period_start:string;period_end:string}>(`SELECT period_start,period_end FROM app.subscriptions WHERE tenant_id=$1 AND status='active' AND period_end>now() ORDER BY created_at DESC LIMIT 1 FOR UPDATE`,[r.session!.tenantId])).rows[0];if(!current)throw Object.assign(new Error('当前没有可切换的有效订阅'),{statusCode:409});const order=(await c.query<{id:string;provider:string;provider_ref:string|null}>(`SELECT o.id,o.provider,o.provider_ref FROM app.payment_orders o JOIN app.plans p ON p.id=o.plan_id WHERE o.tenant_id=$1 AND o.plan_id=$2 AND o.status='paid' AND p.active=true ORDER BY o.paid_at DESC LIMIT 1 FOR UPDATE OF o`,[r.session!.tenantId,b.planId])).rows[0];if(!order)throw Object.assign(new Error('该套餐尚未支付，不能手动启用'),{statusCode:409});await c.query(`UPDATE app.subscriptions SET status='cancelled' WHERE tenant_id=$1 AND status='active'`,[r.session!.tenantId]);return (await c.query(`INSERT INTO app.subscriptions(tenant_id,plan_id,provider,provider_ref,status,period_start,period_end) VALUES($1,$2,$3,$4,'active',$5,$6) RETURNING *`,[r.session!.tenantId,b.planId,order.provider,order.provider_ref??order.id,current.period_start,current.period_end])).rows[0]});await audit(r,'subscription.paid_plan.activate','subscription',subscription.id,{planId:b.planId,method:'paid_order_selection'});return ok(subscription)})
app.post('/api/plans',{preHandler:permit('plans:manage')},async r=>{const b=z.object({code:z.string().regex(/^[a-z][a-z0-9_-]+$/),name:z.string().min(2),description:z.string().default(''),priceCny:z.number().nonnegative(),priceUsd:z.number().nonnegative(),entitlements:z.object({providers:z.number().int().positive().optional(),models:z.number().int().positive().optional(),members:z.number().int().positive().optional()})}).parse(r.body);const row=(await query(`INSERT INTO app.plans(code,name,description,price_cny,price_usd,entitlements) VALUES($1,$2,$3,$4,$5,$6) RETURNING *`,[b.code,b.name,b.description,b.priceCny,b.priceUsd,JSON.stringify(b.entitlements)])).rows[0];await audit(r,'plan.create','plan',row.id);return ok(row)})
// Direct payment routes are registered below; historical aggregate-provider orders remain queryable.
const paymentOrderSelect=`SELECT o.id,o.tenant_id,t.name tenant_name,t.slug tenant_slug,o.plan_id,o.provider,o.amount,o.currency,o.status,o.provider_ref,o.checkout_url,o.provider_channel,o.payment_payload,o.created_at,o.updated_at,o.paid_at,o.cancelled_at,p.code plan_code,p.name plan_name,p.description plan_description,p.billing_period FROM app.payment_orders o JOIN app.tenants t ON t.id=o.tenant_id JOIN app.plans p ON p.id=o.plan_id`
app.get('/api/payment-orders',{preHandler:permit('payments:manage')},async r=>{const q=z.object({scope:z.enum(['current','all']).default('current'),tenantId:z.string().uuid().optional(),status:z.enum(['pending','paid','cancelled','failed','refunded']).optional(),provider:z.enum(['stripe','pingpp','wechat','manual']).optional(),search:z.string().trim().max(100).optional(),page:z.coerce.number().int().positive().default(1),pageSize:z.coerce.number().int().min(5).max(100).default(20)}).parse(r.query),allTenants=q.scope==='all'&&r.session!.permissions.includes('*'),tenantId=allTenants?(q.tenantId??null):r.session!.tenantId,search=q.search?`%${q.search}%`:null,offset=(q.page-1)*q.pageSize,params=[tenantId,q.status??null,q.provider??null,search],where=`($1::uuid IS NULL OR o.tenant_id=$1) AND ($2::text IS NULL OR o.status=$2) AND ($3::text IS NULL OR o.provider=$3) AND ($4::text IS NULL OR o.id::text ILIKE $4 OR p.name ILIKE $4 OR t.name ILIKE $4 OR t.slug ILIKE $4 OR coalesce(o.provider_ref,'') ILIKE $4)`;const total=Number((await query(`SELECT count(*) count FROM app.payment_orders o JOIN app.tenants t ON t.id=o.tenant_id JOIN app.plans p ON p.id=o.plan_id WHERE ${where}`,params)).rows[0].count),items=(await query(`${paymentOrderSelect} WHERE ${where} ORDER BY o.created_at DESC LIMIT $5 OFFSET $6`,[...params,q.pageSize,offset])).rows;return ok({items,total,page:q.page,pageSize:q.pageSize,pages:Math.max(1,Math.ceil(total/q.pageSize))})})
app.get('/api/payment-orders/:id',{preHandler:permit('payments:manage')},async r=>{const id=z.string().uuid().parse((r.params as {id:string}).id),scope=z.enum(['current','all']).default('current').parse((r.query as {scope?:string}).scope),tenantId=scope==='all'&&r.session!.permissions.includes('*')?null:r.session!.tenantId,row=(await query(`${paymentOrderSelect} WHERE o.id=$1 AND ($2::uuid IS NULL OR o.tenant_id=$2)`,[id,tenantId])).rows[0];if(!row)throw Object.assign(new Error('支付订单不存在'),{statusCode:404});return ok(row)})
app.post('/api/payment-orders/:id/pay',{preHandler:permit('payments:manage')},async r=>{const id=z.string().uuid().parse((r.params as {id:string}).id),row=(await query(`${paymentOrderSelect} WHERE o.id=$1 AND o.tenant_id=$2`,[id,r.session!.tenantId])).rows[0];if(!row)throw Object.assign(new Error('支付订单不存在'),{statusCode:404});if(row.status!=='pending')throw Object.assign(new Error('只有待支付订单可以继续支付'),{statusCode:409});if(!row.checkout_url)throw Object.assign(new Error('支付渠道尚未生成支付二维码，请在接入支付网关后重试'),{statusCode:409});await audit(r,'payment.order.pay','payment_order',id,{provider:row.provider});const payload=row.payment_payload??{};return ok({checkoutUrl:row.checkout_url,qrCodeDataUrl:payload.qrCodeDataUrl??'',channel:row.provider_channel??'',providerRef:row.provider_ref})})
app.post('/api/payment-orders/:id/cancel',{preHandler:permit('payments:manage')},async r=>{const id=z.string().uuid().parse((r.params as {id:string}).id),row=(await query(`UPDATE app.payment_orders SET status='cancelled',cancelled_at=now(),updated_at=now() WHERE id=$1 AND tenant_id=$2 AND status='pending' RETURNING id,status,cancelled_at`,[id,r.session!.tenantId])).rows[0];if(!row){const current=(await query(`SELECT status FROM app.payment_orders WHERE id=$1 AND tenant_id=$2`,[id,r.session!.tenantId])).rows[0];if(!current)throw Object.assign(new Error('支付订单不存在'),{statusCode:404});throw Object.assign(new Error('只有待支付订单可以取消'),{statusCode:409})}await audit(r,'payment.order.cancel','payment_order',id);return ok(row)})
app.delete('/api/payment-orders/:id',{preHandler:permit('payments:manage')},async r=>{const id=z.string().uuid().parse((r.params as {id:string}).id),row=(await query(`DELETE FROM app.payment_orders WHERE id=$1 AND tenant_id=$2 AND status IN ('cancelled','failed') RETURNING id`,[id,r.session!.tenantId])).rows[0];if(!row){const current=(await query(`SELECT status FROM app.payment_orders WHERE id=$1 AND tenant_id=$2`,[id,r.session!.tenantId])).rows[0];if(!current)throw Object.assign(new Error('支付订单不存在'),{statusCode:404});throw Object.assign(new Error('只能删除已取消或失败的订单'),{statusCode:409})}await audit(r,'payment.order.delete','payment_order',id);return ok(true)})
// WeChat Pay API v3 callbacks are registered below.
app.post('/api/settings/brand-logo',{preHandler:permit('settings:manage')},async r=>{const part=await r.file();if(!part)throw Object.assign(new Error('请选择企业 Logo 文件'),{statusCode:400});const mimeExtensions:Record<string,string>={'image/png':'png','image/jpeg':'jpg','image/webp':'webp','image/svg+xml':'svg'},extension=mimeExtensions[part.mimetype];if(!extension)throw Object.assign(new Error('企业 Logo 仅支持 PNG、JPG、WebP 或 SVG 图片'),{statusCode:400});const content=await part.toBuffer();if(part.file.truncated||content.length>2*1024*1024)throw Object.assign(new Error('企业 Logo 文件不能超过 2MB'),{statusCode:400});const tenantId=r.session!.tenantId,path=join(config.uploadDir,tenantId,'brand',`${randomUUID()}.${extension}`);await mkdir(join(config.uploadDir,tenantId,'brand'),{recursive:true});await writeFile(path,content);await query(`UPDATE app.tenants SET brand_logo_path=$1,brand_logo_mime_type=$2,updated_at=now() WHERE id=$3`,[path,part.mimetype,tenantId]);await audit(r,'tenant.brand.logo.update','tenant',tenantId,{mimeType:part.mimetype,sizeBytes:content.length});return ok({brand_logo_url:`/api/tenant-brand/${tenantId}/logo?updatedAt=${Date.now()}`})})
app.delete('/api/settings/brand-logo',{preHandler:permit('settings:manage')},async r=>{await query(`UPDATE app.tenants SET brand_logo_path=NULL,brand_logo_mime_type=NULL,updated_at=now() WHERE id=$1`,[r.session!.tenantId]);await audit(r,'tenant.brand.logo.remove','tenant',r.session!.tenantId);return ok(true)})
app.patch('/api/settings',{preHandler:permit('settings:manage')},async r=>{const b=z.object({name:z.string().min(2).max(100),description:z.string().max(2000),locale:z.string(),timezone:z.string(),settings:z.record(z.string(),z.boolean())}).parse(r.body);const row=(await query(`UPDATE app.tenants SET name=$1,description=$2,locale=$3,timezone=$4,settings=$5,updated_at=now() WHERE id=$6 RETURNING *`,[b.name,b.description,b.locale,b.timezone,JSON.stringify(b.settings),r.session!.tenantId])).rows[0];await audit(r,'tenant.update','tenant',r.session!.tenantId);return ok(row)})
const channelType=z.enum(['feishu','lark','dingtalk','notion','wecom','wechat_official','web','personal_wechat'])
const channelScope=z.enum(['member','tenant'])
app.get('/api/settings/channel-notifications',{preHandler:auth},async r=>{const scope=channelScope.default('member').parse((r.query as {scope?:string}).scope),userId=scope==='member'?r.session!.userId:null;if(scope==='tenant')assertPermission(r.session!,'settings:manage');const rows=(await query(`SELECT id,channel_type,name,public_config,callback_url,encrypted_secret_config IS NOT NULL secret_configured,user_id IS NULL is_tenant_default FROM app.channel_notification_accounts WHERE tenant_id=$1 AND user_id IS NOT DISTINCT FROM $2::uuid ORDER BY channel_type`,[r.session!.tenantId,userId])).rows;return ok(rows)})
app.put('/api/settings/channel-notifications/:scope/:type',{preHandler:auth},async r=>{const params=z.object({scope:channelScope,type:channelType}).parse(r.params),b=z.object({name:z.string().trim().min(1).max(120),publicConfig:z.record(z.string(),z.string()).default({}),secretConfig:z.record(z.string(),z.string()).default({}),callbackUrl:z.string().trim().url().or(z.literal('')).default('')}).parse(r.body),userId=params.scope==='member'?r.session!.userId:null;if(params.scope==='tenant')assertPermission(r.session!,'settings:manage');const existing=(await query<{encrypted_secret_config:string|null}>(`SELECT encrypted_secret_config FROM app.channel_notification_accounts WHERE tenant_id=$1 AND user_id IS NOT DISTINCT FROM $2::uuid AND channel_type=$3`,[r.session!.tenantId,userId,params.type])).rows[0],secrets=Object.fromEntries(Object.entries(b.secretConfig).filter(([,value])=>value.trim())),encryptedSecrets=Object.keys(secrets).length?encrypt(JSON.stringify(secrets)):existing?.encrypted_secret_config??null,values=[r.session!.tenantId,params.type,b.name,JSON.stringify(b.publicConfig),encryptedSecrets,b.callbackUrl||null],sql=params.scope==='member'?`INSERT INTO app.channel_notification_accounts(tenant_id,user_id,channel_type,name,public_config,encrypted_secret_config,callback_url) VALUES($1,$7,$2,$3,$4,$5,$6) ON CONFLICT(tenant_id,user_id,channel_type) WHERE user_id IS NOT NULL DO UPDATE SET name=EXCLUDED.name,public_config=EXCLUDED.public_config,encrypted_secret_config=EXCLUDED.encrypted_secret_config,callback_url=EXCLUDED.callback_url,updated_at=now() RETURNING id,channel_type,name,public_config,callback_url,encrypted_secret_config IS NOT NULL secret_configured,false is_tenant_default`:`INSERT INTO app.channel_notification_accounts(tenant_id,user_id,channel_type,name,public_config,encrypted_secret_config,callback_url) VALUES($1,NULL,$2,$3,$4,$5,$6) ON CONFLICT(tenant_id,channel_type) WHERE user_id IS NULL DO UPDATE SET name=EXCLUDED.name,public_config=EXCLUDED.public_config,encrypted_secret_config=EXCLUDED.encrypted_secret_config,callback_url=EXCLUDED.callback_url,updated_at=now() RETURNING id,channel_type,name,public_config,callback_url,encrypted_secret_config IS NOT NULL secret_configured,true is_tenant_default`,row=(await query(sql,params.scope==='member'?[...values,userId]:values)).rows[0];await audit(r,'channel_notification.update','channel_notification',row.id,{scope:params.scope,type:params.type});return ok(row)})
app.delete('/api/settings/channel-notifications/:scope/:type',{preHandler:auth},async r=>{const params=z.object({scope:channelScope,type:channelType}).parse(r.params),userId=params.scope==='member'?r.session!.userId:null;if(params.scope==='tenant')assertPermission(r.session!,'settings:manage');const row=(await query(`DELETE FROM app.channel_notification_accounts WHERE tenant_id=$1 AND user_id IS NOT DISTINCT FROM $2::uuid AND channel_type=$3 RETURNING id`,[r.session!.tenantId,userId,params.type])).rows[0];if(!row)throw Object.assign(new Error('渠道配置不存在'),{statusCode:404});await audit(r,'channel_notification.delete','channel_notification',row.id,{scope:params.scope,type:params.type});return ok(true)})
app.post('/api/channel-notification-webhooks/:type/:accountId',async r=>{const params=z.object({type:channelType,accountId:z.string().uuid()}).parse(r.params),account=(await query<{callback_url:string|null}>(`SELECT callback_url FROM app.channel_notification_accounts WHERE id=$1 AND channel_type=$2`,[params.accountId,params.type])).rows[0];if(!account)throw Object.assign(new Error('渠道配置不存在'),{statusCode:404});if(!account.callback_url)return ok({accepted:true,forwarded:false});const response=await fetch(account.callback_url,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(r.body??{})});if(!response.ok)throw Object.assign(new Error(`业务回调返回 ${response.status}`),{statusCode:502});return ok({accepted:true,forwarded:true})})
registerPaymentRoutes(app,permit,superAdmin)
if(config.production){await app.register(staticPlugin,{root:join(process.cwd(),'dist')});app.setNotFoundHandler((r,reply)=>r.url.startsWith('/api/')?reply.code(404).send({error:'not_found'}):reply.sendFile('index.html'))}
await app.listen({port:config.port,host:'0.0.0.0'})
const close=async()=>{await app.close();await db.end();redis.disconnect()};process.on('SIGINT',close);process.on('SIGTERM',close)
