import { useEffect, useState, type FormEvent } from 'react'
import { Ban, ChevronLeft, ChevronRight, CreditCard, Eye, RefreshCw, Search, Trash2 } from 'lucide-react'
import { ApiError, get, post, remove } from '../api'
import { Badge, Button, Modal, PageHeader } from '../components'
import { PaymentQrModal, type PaymentQr } from '../components/PaymentQrModal'
import { pageMeta } from '../data'
import { useAuth } from '../auth'

type OrderStatus='pending'|'paid'|'cancelled'|'failed'|'refunded'
type PaymentOrder={id:string;tenant_id:string;tenant_name:string;tenant_slug:string;plan_id:string;plan_code:string;plan_name:string;plan_description:string;billing_period:string;provider:'stripe'|'pingpp'|'wechat'|'manual';amount:number;currency:string;status:OrderStatus;provider_ref:string|null;checkout_url:string|null;provider_channel:string|null;payment_payload:{qrCodeDataUrl?:string}|null;created_at:string;updated_at:string;paid_at:string|null;cancelled_at:string|null}
type OrderPage={items:PaymentOrder[];total:number;page:number;pageSize:number;pages:number}
type TenantOption={id:string;name:string;slug:string}
const statusMeta:Record<OrderStatus,{label:string;tone:'green'|'amber'|'gray'|'red'|'blue'}>={pending:{label:'待支付',tone:'amber'},paid:{label:'已支付',tone:'green'},cancelled:{label:'已取消',tone:'gray'},failed:{label:'支付失败',tone:'red'},refunded:{label:'已退款',tone:'blue'}}
const providerLabel={wechat:'微信支付直连',pingpp:'历史聚合支付',stripe:'Stripe',manual:'人工'}
const channelLabel=(value:string|null)=>value==='native'||value==='wx_pub_qr'?'微信扫码':value??'—'
const date=(value:string|null)=>value?new Date(value).toLocaleString('zh-CN'):'—'
const money=(order:PaymentOrder)=>new Intl.NumberFormat('zh-CN',{style:'currency',currency:order.currency}).format(Number(order.amount))

export function PaymentOrdersPage({notify}:{notify:(message:string)=>void}){
  const{identity}=useAuth(),isSuperAdmin=identity!.user.permissions.includes('*')
  const[data,setData]=useState<OrderPage|null>(null)
  const[tenants,setTenants]=useState<TenantOption[]>([])
  const[tenantId,setTenantId]=useState('')
  const[status,setStatus]=useState('')
  const[provider,setProvider]=useState('')
  const[search,setSearch]=useState('')
  const[query,setQuery]=useState('')
  const[page,setPage]=useState(1)
  const[detail,setDetail]=useState<PaymentOrder|null>(null)
  const[payment,setPayment]=useState<PaymentQr|null>(null)
  const[busy,setBusy]=useState('')
  const fail=(e:unknown)=>notify(e instanceof ApiError?e.message:'订单操作失败')
  const load=async()=>{const params=new URLSearchParams({page:String(page),pageSize:'20'});if(isSuperAdmin){params.set('scope','all');if(tenantId)params.set('tenantId',tenantId)}if(status)params.set('status',status);if(provider)params.set('provider',provider);if(query)params.set('search',query);setData(await get<OrderPage>(`/api/payment-orders?${params}`))}
  useEffect(()=>{if(isSuperAdmin)void get<TenantOption[]>('/api/tenants?scope=all').then(setTenants).catch(fail)},[isSuperAdmin])
  useEffect(()=>{void load().catch(fail)},[page,tenantId,status,provider,query])
  const openDetail=async(id:string)=>{try{setDetail(await get<PaymentOrder>(`/api/payment-orders/${id}${isSuperAdmin?'?scope=all':''}`))}catch(e){fail(e)}}
  const openPayment=(order:PaymentOrder,result:{checkoutUrl:string;qrCodeDataUrl?:string;channel?:string;providerRef?:string|null})=>setPayment({checkoutUrl:result.checkoutUrl,qrCodeDataUrl:result.qrCodeDataUrl||order.payment_payload?.qrCodeDataUrl,channel:channelLabel(result.channel??order.provider_channel),providerRef:result.providerRef??order.provider_ref,orderId:order.id,amount:order.amount,currency:order.currency})
  const act=async(order:PaymentOrder,action:'pay'|'cancel'|'delete')=>{if(action==='cancel'&&!confirm('确认取消该待支付订单？'))return;if(action==='delete'&&!confirm('确认永久删除该订单？此操作不可恢复。'))return;setBusy(`${action}:${order.id}`);try{if(action==='pay'){const result=await post<{checkoutUrl:string;qrCodeDataUrl?:string;channel?:string;providerRef?:string|null}>(`/api/payment-orders/${order.id}/pay`,{});openPayment(order,result);notify('请使用微信扫码完成支付')}else if(action==='cancel')await post(`/api/payment-orders/${order.id}/cancel`,{});else await remove(`/api/payment-orders/${order.id}`);if(action!=='pay')setDetail(null);await load();notify(action==='cancel'?'订单已取消':action==='delete'?'订单已删除':'支付二维码已打开')}catch(e){fail(e)}finally{setBusy('')}}
  const submitSearch=(event:FormEvent)=>{event.preventDefault();setPage(1);setQuery(search.trim())}
  return <div className="page payment-orders-page">
    <PageHeader {...pageMeta['payment-orders']}><Button variant="secondary" icon={false} onClick={()=>void load()}><RefreshCw size={15}/>刷新</Button></PageHeader>
    <div className="order-summary-grid"><div className="card"><span>订单总数</span><b>{data?.total??0}</b></div><div className="card"><span>当前页待支付</span><b>{data?.items.filter(x=>x.status==='pending').length??0}</b></div><div className="card"><span>当前页已支付</span><b>{data?.items.filter(x=>x.status==='paid').length??0}</b></div></div>
    <div className="order-toolbar"><form className="order-search" onSubmit={submitSearch}><Search/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder={isSuperAdmin?'订单号、租户、套餐或渠道流水号':'订单号、套餐或渠道流水号'}/><button>搜索</button></form>{isSuperAdmin&&<select aria-label="租户" value={tenantId} onChange={e=>{setPage(1);setTenantId(e.target.value)}}><option value="">全部租户</option>{tenants.map(tenant=><option key={tenant.id} value={tenant.id}>{tenant.name}（{tenant.slug}）</option>)}</select>}<select value={status} onChange={e=>{setPage(1);setStatus(e.target.value)}}><option value="">全部状态</option>{Object.entries(statusMeta).map(([key,item])=><option value={key} key={key}>{item.label}</option>)}</select><select value={provider} onChange={e=>{setPage(1);setProvider(e.target.value)}}><option value="">全部渠道</option><option value="wechat">微信支付直连</option><option value="pingpp">历史聚合支付</option><option value="stripe">Stripe</option><option value="manual">人工</option></select></div>
    <div className="card table-card order-table"><table><thead><tr><th>订单 / 套餐</th>{isSuperAdmin&&<th>所属租户</th>}<th>渠道</th><th>金额</th><th>状态</th><th>创建时间</th><th>操作</th></tr></thead><tbody>{data?.items.map(order=>{const canOperate=order.tenant_id===identity!.user.tenantId;return <tr key={order.id}><td><div className="order-id-cell"><b>{order.plan_name}</b><code>{order.id}</code></div></td>{isSuperAdmin&&<td><div className="order-tenant-cell"><b>{order.tenant_name}</b><small>{order.tenant_slug}</small></div></td>}<td>{providerLabel[order.provider]}{order.provider_channel&&<small className="order-channel">{channelLabel(order.provider_channel)}</small>}</td><td><b>{money(order)}</b></td><td><Badge tone={statusMeta[order.status].tone}>{statusMeta[order.status].label}</Badge></td><td>{date(order.created_at)}</td><td><div className="order-actions"><button title="查看详情" onClick={()=>void openDetail(order.id)}><Eye/></button>{canOperate&&order.status==='pending'&&<><button className="pay" disabled={!!busy} onClick={()=>void act(order,'pay')}><CreditCard/>支付</button><button disabled={!!busy} onClick={()=>void act(order,'cancel')}><Ban/>取消</button></>}{canOperate&&['cancelled','failed'].includes(order.status)&&<button className="delete" disabled={!!busy} onClick={()=>void act(order,'delete')}><Trash2/>删除</button>}</div></td></tr>})}</tbody></table>{data&&!data.items.length&&<div className="order-empty"><CreditCard/><b>暂无匹配订单</b><span>{isSuperAdmin?'当前筛选范围内没有支付订单。':'可前往“订阅与套餐”创建支付订单。'}</span></div>}</div>
    {data&&data.total>0&&<div className="order-pagination"><span>共 {data.total} 条，第 {data.page} / {data.pages} 页</span><div><button disabled={data.page<=1} onClick={()=>setPage(x=>x-1)}><ChevronLeft/>上一页</button><button disabled={data.page>=data.pages} onClick={()=>setPage(x=>x+1)}>下一页<ChevronRight/></button></div></div>}
    {detail&&<Modal wide title="支付订单详情" onClose={()=>setDetail(null)} footer={<><Button variant="secondary" icon={false} onClick={()=>setDetail(null)}>关闭</Button>{detail.tenant_id===identity!.user.tenantId&&detail.status==='pending'&&<Button icon={false} disabled={!!busy} onClick={()=>void act(detail,'pay')}><CreditCard size={15}/>继续支付</Button>}</>}><div className="order-detail-head"><div><span>订单状态</span><Badge tone={statusMeta[detail.status].tone}>{statusMeta[detail.status].label}</Badge></div><strong>{money(detail)}</strong></div><dl className="order-detail-grid"><div><dt>订单号</dt><dd><code>{detail.id}</code></dd></div><div><dt>套餐</dt><dd>{detail.plan_name}</dd></div>{isSuperAdmin&&<div><dt>所属租户</dt><dd>{detail.tenant_name}（{detail.tenant_slug}）</dd></div>}<div><dt>支付渠道</dt><dd>{providerLabel[detail.provider]} · {channelLabel(detail.provider_channel)}</dd></div><div><dt>结算周期</dt><dd>{detail.billing_period==='year'?'年付':'月付'}</dd></div><div><dt>渠道流水号</dt><dd>{detail.provider_ref??'尚未生成'}</dd></div><div><dt>创建时间</dt><dd>{date(detail.created_at)}</dd></div><div><dt>支付时间</dt><dd>{date(detail.paid_at)}</dd></div><div><dt>取消时间</dt><dd>{date(detail.cancelled_at)}</dd></div></dl>{!detail.checkout_url&&detail.status==='pending'&&<div className="order-payment-notice">该订单尚未生成支付二维码。订单会保持待支付状态，不会被标记为支付成功。</div>}{detail.checkout_url&&detail.status==='pending'&&<div className="order-payment-notice success">已生成微信支付二维码。支付成功后必须通过微信支付 API v3 回调验签和金额校验才会开通订阅。</div>}<div className="order-detail-actions">{detail.tenant_id===identity!.user.tenantId&&detail.status==='pending'&&<Button variant="secondary" icon={false} disabled={!!busy} onClick={()=>void act(detail,'cancel')}><Ban size={15}/>取消订单</Button>}{detail.tenant_id===identity!.user.tenantId&&['cancelled','failed'].includes(detail.status)&&<Button variant="danger" icon={false} disabled={!!busy} onClick={()=>void act(detail,'delete')}><Trash2 size={15}/>删除订单</Button>}</div></Modal>}
    {payment&&<PaymentQrModal payment={payment} onClose={()=>setPayment(null)} onRefresh={()=>void load()}/>} 
  </div>
}