import { useEffect, useState } from 'react'
import { CheckCircle2, CreditCard, Globe2, KeyRound, LockKeyhole, MessageCircle, QrCode, Save, Server, Trash2 } from 'lucide-react'
import { ApiError, get, put, remove } from '../api'
import { Button } from '../components'

type TenantOption={id:string;name:string;slug:string}
type PaymentConfig={configured:boolean;scopeConfigured:boolean;source:'tenant_override'|'platform'|'environment'|null;scope:'platform'|'tenant_override';platformTenantId:string;targetTenant:TenantOption;appId:string;merchantId:string;merchantSerialNo:string;wechatPayPublicKeyId:string;privateKeyMasked:string;apiV3KeyMasked:string;wechatPayPublicKeyMasked:string;notifyUrl:string}

export function WechatPaySettings({notify}:{notify:(message:string)=>void}){
  const[config,setConfig]=useState<PaymentConfig|null>(null),[tenants,setTenants]=useState<TenantOption[]>([]),[targetTenantId,setTargetTenantId]=useState('')
  const[tab,setTab]=useState<'domestic'|'international'>('domestic')
  const[appId,setAppId]=useState(''),[merchantId,setMerchantId]=useState(''),[merchantSerialNo,setMerchantSerialNo]=useState('')
  const[privateKey,setPrivateKey]=useState(''),[apiV3Key,setApiV3Key]=useState(''),[wechatPayPublicKeyId,setWechatPayPublicKeyId]=useState(''),[wechatPayPublicKey,setWechatPayPublicKey]=useState(''),[notifyUrl,setNotifyUrl]=useState('')
  const[loading,setLoading]=useState(true),[saving,setSaving]=useState(false)
  const fail=(error:unknown)=>notify(error instanceof ApiError?error.message:'支付配置操作失败')
  const clearSecrets=()=>{setPrivateKey('');setApiV3Key('');setWechatPayPublicKey('')}
  const applyConfig=(next:PaymentConfig)=>{setConfig(next);setTargetTenantId(next.targetTenant.id);setAppId(next.appId??'');setMerchantId(next.merchantId??'');setMerchantSerialNo(next.merchantSerialNo??'');setWechatPayPublicKeyId(next.wechatPayPublicKeyId??'');setNotifyUrl(next.notifyUrl??'');clearSecrets()}
  const load=async(tenantId?:string)=>{setLoading(true);try{const suffix=tenantId?`?tenantId=${encodeURIComponent(tenantId)}`:'';applyConfig(await get<PaymentConfig>(`/api/settings/payment/wechat${suffix}`))}catch(error){fail(error)}finally{setLoading(false)}}
  useEffect(()=>{void Promise.all([get<TenantOption[]>('/api/tenants?scope=all').then(setTenants),load()]).catch(fail)},[])
  const changeTarget=(tenantId:string)=>{setTargetTenantId(tenantId);void load(tenantId)}
  const save=async()=>{if(![appId,merchantId,merchantSerialNo,wechatPayPublicKeyId].every(value=>value.trim()))return notify('请填写全部商户标识信息');if(!config?.scopeConfigured&&(!privateKey.trim()||!apiV3Key||!wechatPayPublicKey.trim()))return notify('首次配置当前作用域时必须填写全部密钥和公钥');if(apiV3Key&&new TextEncoder().encode(apiV3Key).length!==32)return notify('API v3 密钥必须正好为 32 字节');if(config?.scope==='platform'&&!notifyUrl.trim())return notify('平台默认配置必须填写支付回调地址');setSaving(true);try{const next=await put<PaymentConfig>('/api/settings/payment/wechat',{tenantId:targetTenantId,appId:appId.trim(),merchantId:merchantId.trim(),merchantSerialNo:merchantSerialNo.trim(),privateKey:privateKey.trim()||undefined,apiV3Key:apiV3Key||undefined,wechatPayPublicKeyId:wechatPayPublicKeyId.trim(),wechatPayPublicKey:wechatPayPublicKey.trim()||undefined,notifyUrl:config?.scope==='platform'?notifyUrl.trim():undefined,clear:false});applyConfig(next);notify(config?.scope==='platform'?'平台默认微信支付配置已加密保存':'租户微信支付覆盖配置已加密保存')}catch(error){fail(error)}finally{setSaving(false)}}
  const clear=async()=>{const fallback=config?.scope==='platform'?'服务器环境变量':'平台默认配置或服务器环境变量';if(!confirm(`确认删除“${config?.targetTenant.name}”的微信支付配置？删除后将回退使用${fallback}。`))return;setSaving(true);try{await remove(`/api/settings/payment/wechat?tenantId=${encodeURIComponent(targetTenantId)}`);await load(targetTenantId);notify('当前作用域的微信支付配置已删除')}catch(error){fail(error)}finally{setSaving(false)}}
  const sourceText=config?.source==='tenant_override'?'使用该租户专属覆盖凭证':config?.source==='platform'?'使用平台默认凭证':config?.source==='environment'?'使用服务器环境变量灾备配置':'尚无可用配置'
  return <section className="wechat-settings" aria-busy={loading}>
    <div className="payment-region-tabs" role="tablist" aria-label="支付区域"><button role="tab" aria-selected={tab==='domestic'} className={tab==='domestic'?'active':''} onClick={()=>setTab('domestic')}><CreditCard/><span><b>国内支付</b><small>人民币 · CNY</small></span></button><button role="tab" aria-selected={tab==='international'} className={tab==='international'?'active':''} onClick={()=>setTab('international')}><Globe2/><span><b>国际支付</b><small>美元 · USD</small></span></button></div>
    {tab==='domestic'&&<><div className="wechat-overview"><div className="wechat-brand-icon"><MessageCircle/></div><div className="wechat-overview-copy"><div className="wechat-title-line"><h2>微信支付直连</h2><span className={config?.configured?'enabled':''}>{loading?'读取中':config?.configured?'已启用':'未配置'}</span></div><p>平台直接调用微信支付 API v3 Native 下单。租户覆盖优先于平台默认配置，环境变量仅作为灾备回退。</p></div><div className="wechat-channel"><QrCode/><span><small>支付产品</small><b>Native 扫码支付</b></span></div></div>
      <div className="payment-scope-card"><label className="field"><span>配置作用域</span><select disabled={loading||saving} value={targetTenantId} onChange={event=>changeTarget(event.target.value)}>{tenants.map(tenant=><option key={tenant.id} value={tenant.id}>{tenant.id===config?.platformTenantId?'平台默认配置':`租户覆盖 · ${tenant.name}`}（{tenant.slug}）</option>)}</select><small>所有租户默认使用平台配置；仅在确有独立商户号时创建租户覆盖。</small></label><div><b>{config?.scope==='platform'?'平台默认配置':config?.targetTenant.name||'租户覆盖配置'}</b><span>{config?.scopeConfigured?'当前作用域已单独配置':`当前作用域未单独配置，${sourceText}`}</span></div></div>
      <div className="wechat-settings-grid"><div className="wechat-config-card"><div className="settings-section-heading"><div className="settings-section-icon"><KeyRound/></div><div><h2>微信支付商户配置</h2><p>仅超级管理员可维护。参数来自微信支付商户平台和已绑定的 AppID。</p></div></div><div className={`credential-status ${config?.configured?'configured':''}`}><span>{config?.configured?<CheckCircle2/>:<Server/>}{config?.configured?'直连凭证可用':'等待配置'}</span><small>{sourceText}</small></div>
        <div className="form-grid payment-credential-form"><label className="field"><span>AppID</span><input placeholder="wx..." disabled={loading||saving} value={appId} onChange={event=>setAppId(event.target.value)}/><small>需与微信支付商户号绑定。</small></label><label className="field"><span>微信支付商户号</span><input placeholder="mchid" disabled={loading||saving} value={merchantId} onChange={event=>setMerchantId(event.target.value)}/></label><label className="field full"><span>商户 API 证书序列号</span><input placeholder="证书序列号" disabled={loading||saving} value={merchantSerialNo} onChange={event=>setMerchantSerialNo(event.target.value)}/></label><label className="field full"><span>商户 API 私钥</span><textarea rows={5} autoComplete="off" placeholder={config?.privateKeyMasked||'-----BEGIN PRIVATE KEY-----'} disabled={loading||saving} value={privateKey} onChange={event=>setPrivateKey(event.target.value)}/><small>{config?.scopeConfigured?'留空保留当前作用域的私钥；填写后将轮换。':'首次配置当前作用域时必须填写有效 PEM 私钥。'}</small></label><label className="field full"><span>API v3 密钥</span><input type="password" autoComplete="new-password" maxLength={32} placeholder={config?.apiV3KeyMasked||'32 字节 API v3 密钥'} disabled={loading||saving} value={apiV3Key} onChange={event=>setApiV3Key(event.target.value)}/><small>用于解密支付成功回调，必须正好为 32 字节。</small></label><label className="field full"><span>微信支付公钥 ID</span><input placeholder="PUB_KEY_ID_..." disabled={loading||saving} value={wechatPayPublicKeyId} onChange={event=>setWechatPayPublicKeyId(event.target.value)}/><small>用于匹配应答和 Webhook 验签公钥。</small></label><label className="field full"><span>微信支付公钥</span><textarea rows={5} autoComplete="off" placeholder={config?.wechatPayPublicKeyMasked||'-----BEGIN PUBLIC KEY-----'} disabled={loading||saving} value={wechatPayPublicKey} onChange={event=>setWechatPayPublicKey(event.target.value)}/><small>{config?.scopeConfigured?'留空保留当前作用域的公钥；轮换后请及时更新。':'首次配置当前作用域时必须填写有效 PEM 公钥。'}</small></label><label className="field full"><span>支付回调地址</span><input value={notifyUrl} disabled={loading||saving||config?.scope!=='platform'} placeholder="https://api.example.com/api/billing/webhooks/wechat" onChange={event=>setNotifyUrl(event.target.value)}/><small>{config?.scope==='platform'?'统一回调入口；生产环境必须为微信可访问的公网 HTTPS 地址。':'租户覆盖统一使用平台默认回调地址，不单独配置。'}</small></label></div>
        <div className="credential-actions"><Button icon={false} disabled={loading||saving||!appId.trim()} onClick={()=>void save()}><Save size={15}/>{saving?'保存中...':'保存当前作用域'}</Button>{config?.scopeConfigured&&<Button variant="danger" icon={false} disabled={saving} onClick={()=>void clear()}><Trash2 size={15}/>删除当前作用域配置</Button>}</div></div>
        <aside className="wechat-help-card"><h3>配置优先级</h3><ol><li><span>1</span><p><b>租户专属覆盖</b><small>仅为需要独立商户号的租户创建。</small></p></li><li><span>2</span><p><b>平台默认配置</b><small>所有未覆盖租户统一使用。</small></p></li><li><span>3</span><p><b>环境变量灾备</b><small>数据库无可用配置时才回退。</small></p></li></ol><div className="security-note"><LockKeyhole/><span><b>安全存储与验签</b><small>私钥、API v3 密钥和微信支付公钥均加密存储；订单只有在回调验签、解密、商户号、金额和币种全部校验通过后才会生效。</small></span></div></aside></div></>}
    {tab==='international'&&<div className="international-payment-card"><div className="international-payment-icon"><Globe2/></div><div><div className="wechat-title-line"><h2>国际支付</h2><span>待接入</span></div><p>国际支付与国内支付独立配置。当前预留 Stripe 美元支付，尚未开放真实下单和 Webhook，不会伪造支付成功。</p><div className="international-provider"><b>Stripe</b><small>银行卡 · USD</small><em>未启用</em></div></div></div>}
  </section>
}